name: Run data linker

concurrency:
  group: ${{ github.ref }}-data-linker
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    name: "Test job"
    runs-on: ubuntu-latest
    inputs:

    steps:
      - name: Test step
        run: echo "Hello, ${{ inputs.name }}!"
