name: Plan and deploy to production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  infrastructure:
    uses: jordanallen-dev/reusable-terraform-workflow/.github/workflows/terraform.yml@main
    with:
      module-path: infra
      apply-environment: production
      node-version: 16.0.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
