on:
  pull_request: {}
  push:
    branches:
      - main

name: Run automated tests

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dispatch
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm ci
      - run: npm run test
